services:
  # Tomcat
  tomcat:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - TOMCAT_USERNAME=root
      - TOMCAT_PASSWORD=7355608
    links:
      - db:mysql
    ports:
      - 8180:8080
    volumes:
      - ./Service/target/Service-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/Service-1.0-SNAPSHOT.war
    networks:
      - avanzada

  # Database
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 7355608
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: 7355608
    networks:
      - avanzada

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8183:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 7355608
    networks:
      - avanzada

networks:
  avanzada:

volumes:
  db_data: